name: r2h5ad
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - r-base>=4.1
  - r-seurat>=5.0
  - r-seuratobject
  - r-qs
  - r-hdf5r
  - r-jsonlite
  - r-matrix
  - r-remotes
  - anndata>=0.12
  - scanpy>=1.12
  - pip
